---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "go",
      "gomod",
      "gowork",
      "gosum",
      "rust",
      "c",
      "cpp",
      "python",
      "lua",
      "luadoc",
      "javascript",
      "typescript",
      "tsx",
      "bash",
      "css",
      "dockerfile",
      "graphql",
      "hcl",
      "http",
      "html",
      "java",
      "json",
      "jsonc",
      "proto",
      "regex",
      "rego",
      "toml",
      "vim",
      "vimdoc",
      "yaml",
      "make",
      "markdown",
      "markdown_inline",
      "sql",
      "prisma",
      "mermaid",
    },
    highlight = {
      enable = true,
      disable = { "yaml" },
    },
    indent = { enable = true },
    auto_install = true,
  },
}
